### ISSUE TITLE
need to update leftgrip_sprint

### ISSUE THREAD

**Issue by dimidr0id** [DaXcess/LCVR-Controller-Profiles#32]
it is difficult to press sprint, you need to change it for version 1.1.2
[profile.inputactions.json](https://github.com/DaXcess/LCVR-Controller-Profiles/files/14019304/profile.inputactions.json)

**Comment by DaXcess** [comment]
If you want to change a profile, please send a pull request following the process in the [README.](/DaXcess/LCVR-Controller-Profiles/blob/main/README.md#adding-your-profile)
